### DISCUSSION TITLE
How to get repo ID and category-ID for my repo?

### DISCUSSION THREAD

**Discussion by neelravi** [giscus/giscus#144] [Q&A] [answered]
I have used giscus in my static website. However, it does not work because I have no idea what to put in the repo-id and category-id fields.
```yaml
  giscus:
    repo:                "neelravi/website-comments"
    repo-id:             "???"
    category:            "Announcements"
    category-id:         "???"
    mapping:             "pathname"
    reaction-enabled:    "1"
    theme:               "light"
    crossorigin:         "anonymous"
```
I am using this in a Hugo generator.
Any suggestions are very welcome!
