### ISSUE TITLE
Changing Comment Fonts

### ISSUE THREAD

**Issue by alidehkhodaei** [giscus/giscus#1059]
Hi, how can I change the font of comments?
Please guide me.

**Comment by rea1shane** [comment]
Use cutom theme and add following:

```css
main {
  font-family: "Nunito Sans", sans-serif;
}

/* for code */
code,
kbd,
pre,
samp {
  font-family: "Monaco", monospace;
}

```
