### ISSUE TITLE
[suggestion] expose font family variables for custom themes

### ISSUE THREAD

**Issue by KagamiChan** [giscus/giscus#1369]
#1059 provides an example of overriding default fonts, but it turns out the snippet is insufficient for monospace because there're more selectors that has tailwindcss `font-mono` applied

https://github.com/giscus/giscus/blob/d85cb25af82b316e83ffa3e6231f33877c77c35d/styles/base.css#L305-L310

https://github.com/giscus/giscus/blob/d85cb25af82b316e83ffa3e6231f33877c77c35d/styles/base.css#L356-L361

https://github.com/giscus/giscus/blob/d85cb25af82b316e83ffa3e6231f33877c77c35d/styles/base.css#L371-L375

https://github.com/giscus/giscus/blob/d85cb25af82b316e83ffa3e6231f33877c77c35d/styles/base.css#L882-L884

https://github.com/giscus/giscus/blob/d85cb25af82b316e83ffa3e6231f33877c77c35d/styles/globals.css#L188-L190

Could we unify all these places and provide a font family css variable so that customizing font family could be easier? I can implement if this feature is agreed,

**Comment by zava810** [comment]
how to keep <Giscus/>  font family same as that of its parent . in [hex8 site](https://hex8.vercel.app) i am using language indepent fonts picker (fontpicker) . user selects fonts here. but as Giscus_theme is having its own font-family , fonts becomes different for Giscus comment.

**Comment by laymonage** [comment]
In custom themes, you can now override the `--font-family-sans` and `--font-family-monospace` variables with the `:host, html` selector:

```css
:host, html {
  --font-family-sans: "Comic Sans MS";
  --font-family-monospace: "Comic Mono";
}
```

If you'd rather use a serif font, you can define your own `--font-family-serif` variable and override the `--font-family-default` variable instead, e.g.

```css
:host, html {
  --font-family-serif: ui-serif, "Georgia", "Cambria", "Times New Roman", "Times", serif;
  --font-family-default: var(--font-family-serif);
}
```

Note that for custom fonts you need to also include the [`@font-face` declarations](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face).
