### ISSUE TITLE
Put the comment box above the comments

### ISSUE THREAD

**Issue by narisuzu** [giscus/giscus#157]
Could you please add a config option that places the comment box above comments.
Currently, if there are a lot of comments already existed, people need to scroll to the bottom to comment.

**Comment by laymonage** [comment]
Hey, thanks for the suggestion. This has been in my mind for a while, but I'm still not sure how to proceed with this. For one, I don't know which one looks better:

### Option A

![image](https://user-images.githubusercontent.com/6379424/128600432-c509fc2b-4b7c-4742-a3a8-3807a286f2db.png)

### Option B

![image](https://user-images.githubusercontent.com/6379424/128600453-fef64e9c-b15c-4476-b92c-2ac58715707f.png)

...and there's also the different combinations of the horizontal line...

---

### However...

While I'm not against this suggestion, I'm trying to minimize the amount of config that's passed on to the `<script>` tag.

**The good news is**, after #158, you can now achieve this with a custom theme by using flex box and tinkering with the order (e.g. using `flex-direction: column-reverse` or `order: 1;` `order: 2;`, etc.

For demonstration, the custom CSS example (https://giscus.app/themes/custom_example.css) can do this. Try entering it in the https://giscus.app, or here's a [direct URL for the widget](https://giscus.app/widget?origin=https%3A%2F%2Fgiscus.app%2F&session=&theme=https://giscus.app/themes/custom_example.css&reactionsEnabled=1&emitMetadata=0&repo=laymonage%2Fgiscus&repoId=MDEwOlJlcG9zaXRvcnkzNTE5NTgwNTM%3D&category=&categoryId=MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyNzk2NTc1&description=A+comments+widget+built+on+GitHub+Discussions.&term=Welcome+to+giscus%21).

That custom CSS example uses the following CSS rules to achieve it:

```css
.gsc-comments > .gsc-header {
  order: 1;
}

.gsc-comments > .gsc-comment-box {
  order: 2;
  margin-bottom: 1rem;
}

.gsc-comments > .gsc-timeline {
  order: 3;
}

.gsc-timeline {
  flex-direction: column-reverse;
}

.gsc-header {
  padding-bottom: 1rem;
}
```
