### ISSUE TITLE
How to remove comments header?

### ISSUE THREAD

**Issue by cycool29** [giscus/giscus#404]
I don't want to show this on my website:

![image](https://user-images.githubusercontent.com/88134003/154427540-a5a8b0eb-36c9-4272-a44f-f89d41b42c09.png)

Is there any way to remove it? 

I tried adding this CSS in my website CSS but it does not work:

```css
.gsc-header {
   display: none;
}
```
